#!/bin/bash
 Help()
 {
   echo "This script search for a keyword in all files in the current directory with a specified extension"
   echo "search_kw [-f] [-k] [-n]"
   echo "f : file extension you are searching kerwords in"
   echo "k : the keyword you are searching for"
   echo "n : number of lines below the line containing the keyword"
 }

 # Get the options
 while getopts ":f:k:n:h" option; do
   case $option in
     h) # display Help
       Help
       exit;;
     f) FILE_EXTENSION=${OPTARG};; # assign variables
     k) KEYWORD=${OPTARG};;
     n) GREP_INPUTS=${OPTARG};;
    \?) # incorrect option
        echo "Error: Invalid option"
        exit;;
   esac
 done

bold=$(tput bold)
normal=$(tput sgr0)


for f in *.${FILE_EXTENSION}
do 
  if [[ $(cat $f | grep ${KEYWORD} -${GREP_INPUTS}n --color=always) ]]; then
    echo ""
    echo "-------------------------------------------------------------"
    echo ${bold}${f}${normal}
    cat $f | grep ${KEYWORD} -${GREP_INPUTS}n --color=always  
    echo "-------------------------------------------------------------"
  fi
done


